package model;
// Generated 11-Apr-2018 22:52:47 by Hibernate Tools 4.3.1



/**
 * Loaitietkiem generated by hbm2java
 */
public class Loaitietkiem  implements java.io.Serializable {


     private int idloaiTietKiem;
     private String tenLtk;
     private int soNgayRut;
     private float laiSuat;
     private Float laiSuatTruocHan;
     private String kyHan;
     private Boolean guiThem;
     private float tienGuiToiThieu;
     private Boolean isActive;
     private String idthamSo;

    public Loaitietkiem() {
    }

	
    public Loaitietkiem(int idloaiTietKiem, String tenLtk, int soNgayRut, float laiSuat, String kyHan, Boolean guiThem, float tienGuiToiThieu, Boolean isActive, String idthamSo) {
        this.idloaiTietKiem = idloaiTietKiem;
        this.tenLtk = tenLtk;
        this.soNgayRut = soNgayRut;
        this.laiSuat = laiSuat;
        this.kyHan = kyHan;
        this.guiThem = guiThem;
        this.tienGuiToiThieu = tienGuiToiThieu;
        this.isActive = isActive;
        this.idthamSo = idthamSo;
    }
    public Loaitietkiem(int idloaiTietKiem, String tenLtk, int soNgayRut, float laiSuat, Float laiSuatTruocHan, String kyHan, Boolean guiThem, float tienGuiToiThieu, Boolean isActive, String idthamSo) {
       this.idloaiTietKiem = idloaiTietKiem;
       this.tenLtk = tenLtk;
       this.soNgayRut = soNgayRut;
       this.laiSuat = laiSuat;
       this.laiSuatTruocHan = laiSuatTruocHan;
       this.kyHan = kyHan;
       this.guiThem = guiThem;
       this.tienGuiToiThieu = tienGuiToiThieu;
       this.isActive = isActive;
       this.idthamSo = idthamSo;
    }
   
    public int getIdloaiTietKiem() {
        return this.idloaiTietKiem;
    }
    
    public void setIdloaiTietKiem(int idloaiTietKiem) {
        this.idloaiTietKiem = idloaiTietKiem;
    }
    public String getTenLtk() {
        return this.tenLtk;
    }
    
    public void setTenLtk(String tenLtk) {
        this.tenLtk = tenLtk;
    }
    public int getSoNgayRut() {
        return this.soNgayRut;
    }
    
    public void setSoNgayRut(int soNgayRut) {
        this.soNgayRut = soNgayRut;
    }
    public float getLaiSuat() {
        return this.laiSuat;
    }
    
    public void setLaiSuat(float laiSuat) {
        this.laiSuat = laiSuat;
    }
    public Float getLaiSuatTruocHan() {
        return this.laiSuatTruocHan;
    }
    
    public void setLaiSuatTruocHan(Float laiSuatTruocHan) {
        this.laiSuatTruocHan = laiSuatTruocHan;
    }
    public String getKyHan() {
        return this.kyHan;
    }
    
    public void setKyHan(String kyHan) {
        this.kyHan = kyHan;
    }
    public Boolean getGuiThem() {
        return this.guiThem;
    }
    
    public void setGuiThem(Boolean guiThem) {
        this.guiThem = guiThem;
    }
    public float getTienGuiToiThieu() {
        return this.tienGuiToiThieu;
    }
    
    public void setTienGuiToiThieu(float tienGuiToiThieu) {
        this.tienGuiToiThieu = tienGuiToiThieu;
    }
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }
    public String getIdthamSo() {
        return this.idthamSo;
    }
    
    public void setIdthamSo(String idthamSo) {
        this.idthamSo = idthamSo;
    }




}


