package model;
// Generated 11-Apr-2018 22:52:47 by Hibernate Tools 4.3.1



/**
 * Nhanvien generated by hbm2java
 */
public class Nhanvien  implements java.io.Serializable {


     private String id;
     private String pass;
     private String name;
     private Integer age;
     private String phone;
     private String email;

    public Nhanvien() {
    }

	
    public Nhanvien(String id, String pass, String name) {
        this.id = id;
        this.pass = pass;
        this.name = name;
    }
    public Nhanvien(String id, String pass, String name, Integer age, String phone, String email) {
       this.id = id;
       this.pass = pass;
       this.name = name;
       this.age = age;
       this.phone = phone;
       this.email = email;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getAge() {
        return this.age;
    }
    
    public void setAge(Integer age) {
        this.age = age;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


