package model;
// Generated 11-Apr-2018 22:52:47 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Phieugui generated by hbm2java
 */
public class Phieugui  implements java.io.Serializable {


     private Integer idphieuGui;
     private String idsoTk;
     private float soTienGui;
     private Date ngayGui;
     private String nguoiGuiTien;

    public Phieugui() {
    }

    public Phieugui(Integer idphieuGui, String idsoTk, float soTienGui, Date ngayGui, String nguoiGuiTien) {
       this.idphieuGui = idphieuGui;
       this.idsoTk = idsoTk;
       this.soTienGui = soTienGui;
       this.ngayGui = ngayGui;
       this.nguoiGuiTien = nguoiGuiTien;
    }
   
    public Integer getIdphieuGui() {
        return this.idphieuGui;
    }
    
    public void setIdphieuGui(Integer idphieuGui) {
        this.idphieuGui = idphieuGui;
    }
    public String getIdsoTk() {
        return this.idsoTk;
    }
    
    public void setIdsoTk(String idsoTk) {
        this.idsoTk = idsoTk;
    }
    public float getSoTienGui() {
        return this.soTienGui;
    }
    
    public void setSoTienGui(float soTienGui) {
        this.soTienGui = soTienGui;
    }
    public Date getNgayGui() {
        return this.ngayGui;
    }
    
    public void setNgayGui(Date ngayGui) {
        this.ngayGui = ngayGui;
    }
    public String getNguoiGuiTien() {
        return this.nguoiGuiTien;
    }
    
    public void setNguoiGuiTien(String nguoiGuiTien) {
        this.nguoiGuiTien = nguoiGuiTien;
    }




}


