package model;
// Generated 11-Apr-2018 22:52:47 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Sotietkiem generated by hbm2java
 */
public class Sotietkiem  implements java.io.Serializable {


     private String idstk;
     private int idloaiTietKiem;
     private String idkh;
     private Date ngayMo;
     private Boolean dongSo;
     private String loaiTien;
     private Date ngayTinhLai;
     private Date ngayDenHan;
     private float tongTien;
     private Boolean isActive;

    public Sotietkiem() {
    }

	
    public Sotietkiem(String idstk, int idloaiTietKiem, String idkh, Boolean dongSo, String loaiTien, float tongTien, Boolean isActive) {
        this.idstk = idstk;
        this.idloaiTietKiem = idloaiTietKiem;
        this.idkh = idkh;
        this.dongSo = dongSo;
        this.loaiTien = loaiTien;
        this.tongTien = tongTien;
        this.isActive = isActive;
    }
    public Sotietkiem(String idstk, int idloaiTietKiem, String idkh, Date ngayMo, Boolean dongSo, String loaiTien, Date ngayTinhLai, Date ngayDenHan, float tongTien, Boolean isActive) {
       this.idstk = idstk;
       this.idloaiTietKiem = idloaiTietKiem;
       this.idkh = idkh;
       this.ngayMo = ngayMo;
       this.dongSo = dongSo;
       this.loaiTien = loaiTien;
       this.ngayTinhLai = ngayTinhLai;
       this.ngayDenHan = ngayDenHan;
       this.tongTien = tongTien;
       this.isActive = isActive;
    }
   
    public String getIdstk() {
        return this.idstk;
    }
    
    public void setIdstk(String idstk) {
        this.idstk = idstk;
    }
    public int getIdloaiTietKiem() {
        return this.idloaiTietKiem;
    }
    
    public void setIdloaiTietKiem(int idloaiTietKiem) {
        this.idloaiTietKiem = idloaiTietKiem;
    }
    public String getIdkh() {
        return this.idkh;
    }
    
    public void setIdkh(String idkh) {
        this.idkh = idkh;
    }
    public Date getNgayMo() {
        return this.ngayMo;
    }
    
    public void setNgayMo(Date ngayMo) {
        this.ngayMo = ngayMo;
    }
    public Boolean getDongSo() {
        return this.dongSo;
    }
    
    public void setDongSo(boolean dongSo) {
        this.dongSo = dongSo;
    }
    public String getLoaiTien() {
        return this.loaiTien;
    }
    
    public void setLoaiTien(String loaiTien) {
        this.loaiTien = loaiTien;
    }
    public Date getNgayTinhLai() {
        return this.ngayTinhLai;
    }
    
    public void setNgayTinhLai(Date ngayTinhLai) {
        this.ngayTinhLai = ngayTinhLai;
    }
    public Date getNgayDenHan() {
        return this.ngayDenHan;
    }
    
    public void setNgayDenHan(Date ngayDenHan) {
        this.ngayDenHan = ngayDenHan;
    }
    public float getTongTien() {
        return this.tongTien;
    }
    
    public void setTongTien(float tongTien) {
        this.tongTien = tongTien;
    }
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }




}


